<a href="https://colab.research.google.com/github/suhyun565/Deeplearning_for_everyone/blob/main/multivariable_linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip uninstall tensorflow

Found existing installation: tensorflow 2.7.0
Uninstalling tensorflow-2.7.0:
  Would remove:
    /usr/local/bin/estimator_ckpt_converter
    /usr/local/bin/import_pb_to_tensorboard
    /usr/local/bin/saved_model_cli
    /usr/local/bin/tensorboard
    /usr/local/bin/tf_upgrade_v2
    /usr/local/bin/tflite_convert
    /usr/local/bin/toco
    /usr/local/bin/toco_from_protos
    /usr/local/lib/python3.7/dist-packages/tensorflow-2.7.0.dist-info/*
    /usr/local/lib/python3.7/dist-packages/tensorflow/*
Proceed (y/n)? y
  Successfully uninstalled tensorflow-2.7.0


In [ ]:
!pip install tensorflow==1.14

In [ ]:
import tensorflow as tf
print(tf.__version__)

In [ ]:
x_data = [[73.,80.,75.],[93.,88.,93.],[89.,91.,90.],[96.,98.,100.],[73.,66.,70.]]
y_data = [[152.],[185.],[180.],[196.],[142.]]

x = tf.placeholder(tf.float32, shape=[None,3])
y = tf.placeholder(tf.float32, shape=[None,1])

w = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]),name='bias')

hypothesis = tf.matmul(x,w)+b
cost = tf.reduce_mean(tf.square(hypothesis - y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
  cost_val,hy_val,_ =sess.run(
      [cost,hypothesis,train], feed_dict={x:x_data, y:y_data})
  if step % 10 ==0:
    print(step,'cost:',cost_val,'\n prediction: \n', hy_val)

0 cost: 39868.395 
 prediction: 
 [[-21.676485]
 [-31.275858]
 [-28.206095]
 [-28.706953]
 [-26.99764 ]]
10 cost: 16.967382 
 prediction: 
 [[154.90436]
 [180.988  ]
 [180.92722]
 [199.03476]
 [134.91226]]
20 cost: 16.52602 
 prediction: 
 [[155.42451]
 [181.64003]
 [181.55576]
 [199.72005]
 [135.4156 ]]
30 cost: 16.44989 
 prediction: 
 [[155.41202]
 [181.65175]
 [181.55345]
 [199.7183 ]
 [135.43054]]
40 cost: 16.374249 
 prediction: 
 [[155.39792]
 [181.66147]
 [181.54922]
 [199.71451]
 [135.44394]]
50 cost: 16.298916 
 prediction: 
 [[155.38387]
 [181.67117]
 [181.54501]
 [199.7107 ]
 [135.45732]]
60 cost: 16.224066 
 prediction: 
 [[155.36986]
 [181.68085]
 [181.54082]
 [199.70691]
 [135.47066]]
70 cost: 16.149546 
 prediction: 
 [[155.3559 ]
 [181.69052]
 [181.53664]
 [199.70314]
 [135.48398]]
80 cost: 16.07549 
 prediction: 
 [[155.34196]
 [181.70013]
 [181.53247]
 [199.69936]
 [135.49724]]
90 cost: 16.00181 
 prediction: 
 [[155.32806]
 [181.70973]
 [181.52829]
 [199.6956 ]
 [13